name: App bug report
about: Report any bugs or errors found on App.
labels: bug
body:

  - type: checkboxes
    id: guidelines
    attributes:
      label: Guidelines
      description: Make sure all the following are correct.
      options:
        - label: It **is not** a duplicate issue.
          required: true
        - label: It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
          required: true
        - label: If provider bug, **it is exclusively** on this Fork.
          required: true
        - label: If related to a provider, I have checked the site and it works, but not the app.
          required: true
          
 - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. Go to '...'
          2. Click on '....'
          3. See error
    validations:
      required: true
      
 - type: input
    id: cloudstream-version
    attributes:
      label: Cloudstream version
      description: |
        You can find your Cloudstream version in **Settings** -> **Check for Update**.
      placeholder: |
        Example: "2.9.22"
    validations:
      required: true
