name: Build App

on:
  workflow_dispatch:

concurrency: 
  group: "release"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get commit count
      run: echo "COMMIT_COUNT=$(git rev-list --count javdev)" >> $GITHUB_ENV
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
        echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/release_keystore.keystore
    - name: Run Gradle
      run: ./gradlew app:assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "jav_r${{ secrets.COMMIT_COUNT }}"
        prerelease: false
        name: "CloudStream-3XXX r${{ secrets.COMMIT_COUNT }}"
        files: |
          app/build/outputs/apk/release/*.apk
        body: |
          [Release notes here](https://github.com/Jacekun/CloudStream-3XXX/blob/javdev/doc/version_log.md)
